name: 'Create Pull Request with deps update'
description: 'This action creates a pull request with updated dependencies'
inputs:
  name:
    description: |-
      Name of the project we are in. 
    required: true
  version:
    description: |-
      Version string to use and update in deps.txt.
    required: true

runs:
  using: "composite"
  steps:
    - name: Checkout the calling repo
      uses: actions/checkout@v4
      with:
        ref: ${{ github.ref }}
        path: repository

    - name: Checkout manticoreseach
      uses: actions/checkout@v4
      env:
        GH_ACTION_REPOSITORY: ${{ github.action_repository }}
        GH_ACTION_REF: ${{ github.action_ref }}
      with:
        repository: '${{ env.GH_ACTION_REPOSITORY }}'
        ref: '${{ env.GH_ACTION_REF }}'
        path: 'manticoresearch'

    - name: Get original commit
      shell: bash
      id: commit
      run: |
        cd manticoresearch
        name=${{ inputs.name }}
        version=$( cat deps.txt | grep "$name" | cut -d' ' -f2 )
        date=$( cat deps.txt | grep "$name" | cut -d' ' -f3 )
        commit=$( cat deps.txt | grep "$name" | cut -d' ' -f4 )
        echo "original_version=$version" >> $GITHUB_OUTPUT
        echo "original_date=$date" >> $GITHUB_OUTPUT
        echo "original_commit=$commit" >> $GITHUB_OUTPUT
        cd ..

    - name: Update deps.txt
      id: deps
      shell: bash
      run: |
        cd manticoresearch
        name=${{ inputs.name }}
        version_string="${{ inputs.version }}"
        echo "version_string=${version_string// /-}" >> $GITHUB_OUTPUT
        sed -i '/^'$name'\s/c\'$name' '"$version_string" deps.txt
        cd ..

    - name: Prepare commit message
      id: commit-message
      shell: bash
      run: |
        cd repository
        repo_url=${{ github.server_url }}/${{ github.repository }}
        changes=$(git log --pretty=format:"[\`%h\`]($repo_url/commit/%H) %s" ${{ steps.commit.outputs.original_commit }}..HEAD)
        name=${{ inputs.name }}
        version_string=${{ inputs.version }}
        branch="update-${name}-version"
        title="Update ${name} version"
        commit="Bump ${name} version to: ${version_string}"
        body_path=$(mktemp)
        echo "Update [${name}](${repo_url}) version to: ${version_string}" > "$body_path"
        echo >> "$body_path"
        echo "$changes" >> "$body_path"
        echo "branch=$branch" >> $GITHUB_OUTPUT
        echo "title=$title" >> $GITHUB_OUTPUT
        echo "commit=$commit" >> $GITHUB_OUTPUT
        echo "body-path=$body_path" >> $GITHUB_OUTPUT
        cd ..

    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v6
      with:
        path: manticoresearch
        token: ${{ github.token }}
        commit-message: ${{ steps.commit-message.outputs.commit }}
        title: ${{ steps.commit-message.outputs.title }}
        body-path: ${{ steps.commit-message.outputs.body-path }}
        branch: ${{ steps.commit-message.outputs.branch }}
        draft: false
