name: 'Create Pull Request with deps update'
description: 'This action creates a pull request with updated dependencies'

inputs:
  name:
    description: |-
      Name of the project we are in. 
    required: true
  version:
    description: |-
      Version string to use and update in deps.txt.
    required: true
  token:
    description: |-
      Github token to use for the pull request.
    required: true

runs:
  using: "composite"
  steps:
    - name: Checkout the calling repo
      uses: actions/checkout@v4
      env:
        GH_REPOSITORY_REF: ${{ github.head_ref || github.ref }}
      with:
        token: ${{ inputs.token }}
        fetch-depth: 50
        ref: ${{ env.GH_REPOSITORY_REF }}
        path: repository

    - name: Checkout manticoreseach
      uses: actions/checkout@v4
      env:
        GH_ACTION_REPOSITORY: ${{ github.action_repository }}
        GH_ACTION_REF: ${{ github.action_ref }}
      with:
        token: ${{ inputs.token }}
        repository: '${{ env.GH_ACTION_REPOSITORY }}'
        ref: '${{ env.GH_ACTION_REF }}'
        path: 'manticoresearch'

    - name: Set up Git
      shell: bash
      run: |
        cd manticoresearch
        git config user.name githubmanticore 
        git config user.email contact@manticoresearch.com

    - name: Get original commit
      shell: bash
      id: commit
      run: |
        cd manticoresearch
        name=${{ inputs.name }}
        version=$( cat deps.txt | grep "$name" | cut -d' ' -f2 )
        date=$( cat deps.txt | grep "$name" | cut -d' ' -f3 )
        commit=$( cat deps.txt | grep "$name" | cut -d' ' -f4 )
        echo "original_version=$version" >> $GITHUB_OUTPUT
        echo "original_date=$date" >> $GITHUB_OUTPUT
        echo "original_commit=$commit" >> $GITHUB_OUTPUT
        cd ..

    - name: Determine branch and target
      id: branch
      shell: bash
      run: |
        echo "branch=update-${{ inputs.name }}-version" >> $GITHUB_OUTPUT
        echo "source_branch=${{ github.head_ref }}" >> $GITHUB_OUTPUT
        echo "target=master" >> $GITHUB_OUTPUT

    - name: Prepare update version branch
      shell: bash
      run: |
        cd manticoresearch
        #
        # Fetch branch or create it
        git fetch origin
        if ! git ls-remote --exit-code --heads origin ${{ steps.branch.outputs.branch }}; then
          git checkout -b ${{ steps.branch.outputs.branch }} origin/master
        else
          git checkout ${{ steps.branch.outputs.branch }}
        fi

        cd ..

    - name: Check and merge source branch
      if: steps.branch.outputs.source_branch != ''
      shell: bash
      run: |
        cd manticoresearch
        # Check if the source branch exists in current repository
        if git ls-remote --exit-code origin ${{ steps.branch.outputs.source_branch }}; then
          echo "Source branch ${{ steps.branch.outputs.source_branch }} found in current repository"

          git fetch origin ${{ steps.branch.outputs.source_branch }}
          git cherry-pick origin/${{ steps.branch.outputs.source_branch }}
          if [ $? -eq 0 ]; then
            echo "Successfully cherry-picked changes from ${{ steps.branch.outputs.source_branch }}"
            git push -u origin ${{ steps.branch.outputs.branch }}
            git push origin :${{ steps.branch.outputs.source_branch }}
          else
            echo "Cherry-pick failed. Manual intervention required."
            git cherry-pick --abort
            exit 1
          fi
        else
          echo "Source branch ${{ steps.branch.outputs.source_branch }} not found in current repository"
        fi
        cd ..


    - name: Update deps.txt
      id: deps
      shell: bash
      run: |
        cd manticoresearch

        # Update deps
        name=${{ inputs.name }}
        version_string="${{ inputs.version }}"
        echo "version_string=${version_string// /-}" >> $GITHUB_OUTPUT
        sed -i '/^'$name'\s/c\'$name' '"$version_string" deps.txt
        cd ..

    - name: Prepare commit message
      id: commit-message
      shell: bash
      run: |
        cd repository
        repo_url=${{ github.server_url }}/${{ github.repository }}
        changes=$(git log --pretty=format:"[\`%h\`]($repo_url/commit/%H) %s" ${{ steps.commit.outputs.original_commit }}..HEAD)
        name=${{ inputs.name }}
        version_string="${{ inputs.version }}"
        title="🆕 Update ${name} version"
        commit="Bump ${name} version to: ${version_string}"
        body_path=$(mktemp)
        echo "Update [${name}](${repo_url}) version to: ${version_string} which includes:" > "$body_path"
        echo >> "$body_path"
        echo "$changes" >> "$body_path"
        echo "title=$title" >> $GITHUB_OUTPUT
        echo "commit=$commit" >> $GITHUB_OUTPUT
        echo "body-path=$body_path" >> $GITHUB_OUTPUT
        echo "branch=${{ steps.branch.outputs.branch }}" >> $GITHUB_OUTPUT

    - name: Create or update Pull Request
      shell: bash
      env:
        GITHUB_TOKEN: ${{ inputs.token }}
        GH_TOKEN: ${{ inputs.token }}
        GH_DEBUG: true
        OWNER: ${{ github.repository_owner }}
        REPO: manticoresearch
      run: |
        cd manticoresearch

        gh auth status --show-token

        if ! git diff --exit-code deps.txt> /dev/null 2>&1; then
          git add deps.txt
          git commit -m "${{ steps.commit-message.outputs.commit }}"
          git push -u origin ${{ steps.branch.outputs.branch }}
        fi

        pr_number=$(gh pr list --head ${{ steps.branch.outputs.branch }} --json number --jq '.[0].number')
        if [ -z "$pr_number" ]; then
          gh pr create --base ${{ steps.branch.outputs.target }} --head ${{ steps.branch.outputs.branch }} \
            --title "${{ steps.commit-message.outputs.title }}" \
            --body-file "${{ steps.commit-message.outputs.body-path }}"
        else
          gh pr edit "$pr_number" \
            --repo "$OWNER/$REPO" \
            --title "${{ steps.commit-message.outputs.title }}" \
            --body-file "${{ steps.commit-message.outputs.body-path }}"
        fi
        cd ..

