'\" t
.\"     Title: wordbreaker
.\"    Author: [see the "Author" section]
.\" Generator: DocBook XSL Stylesheets v1.79.1 <http://docbook.sf.net/>
.\"      Date: 12/13/2018
.\"    Manual: Manticore Search
.\"    Source: 2.7.5
.\"  Language: English
.\"
.TH "WORDBREAKER" "1" "12/13/2018" "2\&.7\&.5" "Manticore Search"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
wordbreaker \- Manticore Search tool to split compounds into individual words
.SH "SYNOPSIS"
.HP \w'\fBwordbreaker\fR\ 'u
\fBwordbreaker\fR {command} [options]
.SH "DESCRIPTION"
.PP
Manticore Search is a collection of programs that aim to provide high quality fulltext search\&.
.PP
\fBwordbreaker\fR
is a tool to split compounds (eg URL parts) into individual words\&.
.SH "COMMANDS"
.PP
The commands are as follows:
.PP
\fBtest\fR \fITESTFILE\fR
.RS 4
do a splitting precision test on TESTFILE
.RE
.PP
\fBbench\fR \fITESTFILE\fR
.RS 4
do a splitting performance benchmark on TESTFILE
.RE
.PP
\fBsplit\fR
.RS 4
do splitting (read from stdin, split, print to stdout)
.RE
.SH "OPTIONS"
.PP
The only currently available option applies to all commands and lets you specify the configuration file:
.PP
\fB\-\-dict\fR\ \&\fIFILENAME\fR
.RS 4
use FILENAME as a frequency dictionary (default is wordbreaker\-dict\&.txt)
.RE
.SH "AUTHOR"
.PP
Manticore Software LTD (https://manticoresearch\&.com)
.SH "COPYRIGHT"
.PP
Copyright 2017\-2023 Manticore Software LTD (https://manticoresearch\&.com), 2008\-2016 Sphinx Technologies Inc (http://sphinxsearch\&.com), 2001\-2016 Andrew Aksyonoff
.PP
Permission is granted to copy, distribute and/or modify this document under the terms of the GNU General Public License, Version 2 any later version published by the Free Software Foundation\&.
.SH "SEE ALSO"
.PP
\fBindexer\fR(1),
\fBsearchd\fR(1),
\fBsearch\fR(1)
.PP
Manticore Search and it\*(Aqs programs are documented fully by the
\fIManticore Search reference manual\fR
available in
/usr/share/doc/manticore\&.
