# Deps versions parsing
file(STRINGS "${MANTICORE_SOURCE_DIR}/deps.txt" lines)
foreach(line ${lines})
  if(line STREQUAL "---")
    break()
  endif()
    message("Parsing deps.txt line: ${line}")
    string(REGEX MATCH "^([^ ]+) ([^ ]+) ([^ ]+) ([^ ]+)" _ ${line})
    string(TOUPPER ${CMAKE_MATCH_1} dep)
    set("${dep}_VERNUM" ${CMAKE_MATCH_2})
    set("${dep}_VERDATE" ${CMAKE_MATCH_3})
    set("${dep}_VERHASH" ${CMAKE_MATCH_4})
    message("${dep} version: ${CMAKE_MATCH_2}-${CMAKE_MATCH_3}-${CMAKE_MATCH_4}")
endforeach()
