#!/bin/sh
set -e
# Automatically added by build_xenial, build_jessie
if [ "$1" = "purge" ] ; then
	update-rc.d manticore remove >/dev/null
	rm -rf /var/lib/manticore
	rm -rf /var/log/manticore
	userdel manticore || true
fi

# In case this system is running systemd, we make systemd reload the unit files
# to pick up changes.
if [ -d /run/systemd/system ] ; then
	systemctl --system daemon-reload >/dev/null || true
fi

#DEBHELPER#
