name: MRE

on:
  pull_request:
    branches: [ master ]
    paths:
      - 'test/clt-tests/sharding/mre.rec'
    types: [opened, synchronize, reopened, labeled, unlabeled]

jobs:
  mre:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - uses: manticoresoftware/clt@0.2.3
        with:
          test_prefix: test/clt-tests/sharding/mre.rec
          image: ghcr.io/manticoresoftware/manticoresearch:test-kit-latest