name: MRE

on:
  push:
    branches: [ test/test-drop-sharded-table ]

jobs:
  mre:
    runs-on: ubuntu-22.04
    container:
      image: ghcr.io/manticoresoftware/manticoresearch:test-kit-latest
    continue-on-error: true
    steps:
      - name: Create manticore-1
        run: |
          set -x
          mkdir -p /tmp/1/data
          cat << EOF > /tmp/1/manticore.conf
          searchd {
            listen = 1306:mysql41
            listen = 1312
            log = /tmp/1/searchd.log
            pid_file = /tmp/1/searchd.pid
            data_dir = /tmp/1/data
            query_log = /tmp/1/query.log
            buddy_path = manticore-executor -n /usr/share/manticore/modules/manticore-buddy/src/main.php --debug
            log_http = /tmp/1/http.log
            diskchunk_flush_write_timeout = -1
          }
          EOF
          searchd -c /tmp/1/manticore.conf  --logreplication
          mkdir -p /tmp/2/data
          cat << EOF > /tmp/2/manticore.conf
          searchd {
            listen = 2306:mysql41
            listen = 2312
            log = /tmp/2/searchd.log
            pid_file = /tmp/2/searchd.pid
            data_dir = /tmp/2/data
            query_log = /tmp/2/query.log
            buddy_path = manticore-executor -n /usr/share/manticore/modules/manticore-buddy/src/main.php --debug
            log_http = /tmp/2/http.log
            diskchunk_flush_write_timeout = -1
          }
          EOF
          searchd -c /tmp/2/manticore.conf  --logreplication
          mysql -h0 -P1306 -e "create cluster c"
          mysql -h0 -P2306 -e "join cluster c at '127.0.0.1:1312'"
          mysql -h0 -P1306 -e "create table c:tbl1(id bigint) shards=2 rf=2 timeout=5" || true
          echo "--------------------------------"
          cat  /tmp/1/query.log
          echo "--------------------------------"
          cat  /tmp/2/query.log
          echo "--------------------------------"
          cat  /tmp/1/searchd.log
          echo "--------------------------------"
          cat  /tmp/2/searchd.log
          echo "--------------------------------"
          cat  /tmp/1/http.log
          echo "--------------------------------"
          cat  /tmp/2/http.log