name: MRE

on:
  push:
    branches: [ test/test-drop-sharded-table ]

jobs:
  mre:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - uses: manticoresoftware/clt@0.6.3
        with:
          test_prefix: test/clt-tests/sharding/mre
          image: ghcr.io/manticoresoftware/manticoresearch:test-kit-latest