name: 📖 Route doc check
run-name: 📖 Route doc check ${{ github.sha }}

on:
  pull_request:
    paths:
      - 'manual/**'
    branches:
      - master
      - manticore-*
  push:
    paths:
      - 'manual/**'
    branches-ignore:
      - master
      - maintenance-release
      - manticore-*

jobs:
  check_docs:
    uses: ./.github/workflows/check_docs.yml
    with:
      repo: ${{ github.event_name == 'pull_request' && github.event.pull_request.head.repo.full_name || github.repository }}
      ref: ${{ github.event_name == 'pull_request' && github.event.pull_request.head.ref || github.ref_name }}
      run_translation: false
